#!/usr/bin/env python3
"""Fix prompts to use only positive descriptions (no negative words)."""
import json

with open('E:/game/assets/resources/config/prompts.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# ===== 1. splash_bg.jpg — pure positive, no "no/avoid/without" =====
data['ui/splash/splash_bg.jpg'] = (
    "Unified visual direction: bright cheerful cartoon adventure, "
    "warm hand-painted animation look, rounded friendly shapes, "
    "soft forest light, clean toy-like materials, saturated natural colors, "
    "gentle highlights, clear mobile readability, cozy family-safe fantasy mood, "
    "consistent with the integrated forest-and-gem interface style used by the current game. "
    "Release quality target: crisp confident outlines, clean edges, "
    "high-resolution details, smooth color gradients, polished lighting, "
    "well-balanced composition, refined shape language, stable colors across the asset set. "
    "Runtime copy rule: all readable copy is provided by Cocos labels and game configuration; "
    "the artwork uses blank calm label areas, decorative leaf curls, paw motifs, "
    "stars, flowers, gems, ribbons, ropes, wood trims, soft cloth shapes, "
    "and simple geometric ornaments only. "
    "Safe world motif: flowers, leaves, mushrooms, crystals, coins, lanterns, "
    "books, tents, tools, clouds, stars, paw marks, soft magic sparkles, "
    "clean adventure props, warm camp details, peaceful ruins reclaimed by nature, "
    "and cheerful elemental scenery. "
    "Target canvas: 1280x720. "
    "Runtime format intent: full opaque rectangular image with rich color "
    "and smooth gradients for JPG export. "
    "Asset role: atmospheric background for the splash screen. "
    "Scene concept: wide forest camp scene viewed from a distance, "
    "gentle morning light through trees, open calm meadow in the center area, "
    "wide panoramic landscape view with horizon in the lower third, "
    "soft sky gradient at top, "
    "reserved open meadow space in the middle of the composition for title text overlay, "
    "subtle path or river leading into the distance, "
    "calm unobtrusive ground detail in the bottom area for menu button placement. "
    "Composition: expansive natural landscape scenery only, "
    "peaceful open woodland atmosphere with soft sunlight, "
    "distant treeline, gentle hills or mountain silhouette. "
    "The reserved areas use calm low-detail lighting, soft ground glow, "
    "gentle shadows, and blank readable surfaces. "
    "Style consistency: same rounded line weight, same warm forest palette, "
    "same gem-and-leaf ornament language across every UI resource. "
    "Production note: artwork contains blank copy zones and decorative visual forms only; "
    "readable game copy is rendered by the engine."
)

# ===== 2. btn_create_confirm.png — pure positive button =====
data['ui/create/btn_create_confirm.png'] = (
    "Unified visual direction: bright cheerful cartoon adventure, "
    "warm hand-painted animation look, rounded friendly shapes, "
    "soft forest light, clean toy-like materials, saturated natural colors, "
    "gentle highlights, clear mobile readability, cozy family-safe fantasy mood, "
    "consistent with the integrated forest-and-gem interface style used by the current game. "
    "Release quality target: crisp confident outlines, clean alpha-ready edges, "
    "high-resolution details, smooth color gradients, polished lighting, "
    "readable silhouette, balanced contrast for small mobile screens, "
    "refined shape language, stable colors across the asset set. "
    "Runtime copy rule: all readable copy is provided by Cocos labels and game configuration; "
    "the artwork uses blank calm label areas, decorative leaf curls, paw motifs, "
    "stars, flowers, gems, ribbons, ropes, wood trims, soft cloth shapes, "
    "and simple geometric ornaments only. "
    "Safe world motif: flowers, leaves, mushrooms, crystals, coins, lanterns, "
    "books, tents, tools, clouds, stars, paw marks, soft magic sparkles, "
    "clean adventure props, warm camp details, peaceful ruins reclaimed by nature, "
    "and cheerful elemental scenery. "
    "Target canvas: 240x80. "
    "Runtime format intent: PNG RGBA workflow with clean alpha extraction "
    "for transparent button overlay. "
    "Asset role: clickable raised button frame for the create screen, "
    "visually reads as a pressable UI element. "
    "Shape concept: a raised rounded rectangular button with gentle drop shadow, "
    "beveled edges suggesting pressability, warm wooden texture, subtle wood grain, "
    "slight inner highlight giving a 3D raised appearance. "
    "The overall shape clearly reads as a clickable button, "
    "with a calm blank center area reserved for runtime label text. "
    "Very subtle decorative leaves and gem accents at left and right ends. "
    "Clean alpha edge for transparent overlay. "
    "Style consistency: same rounded line weight, same warm forest palette, "
    "same gem-and-leaf ornament language across every UI resource. "
    "Production note: artwork contains blank copy zones and decorative visual forms only; "
    "readable game copy is rendered by the engine."
)

# ===== 3. character_card_default.png — empty card frame, positive only =====
data['ui/character/character_card_default.png'] = (
    "Unified visual direction: bright cheerful cartoon adventure, "
    "warm hand-painted animation look, rounded friendly shapes, "
    "soft forest light, clean toy-like materials, saturated natural colors, "
    "gentle highlights, clear mobile readability, cozy family-safe fantasy mood, "
    "consistent with the integrated forest-and-gem interface style used by the current game. "
    "Release quality target: crisp confident outlines, clean alpha-ready edges, "
    "high-resolution details, smooth color gradients, polished lighting, "
    "readable silhouette, balanced contrast for small mobile screens, "
    "refined shape language, stable colors across the asset set. "
    "Runtime copy rule: all readable copy is provided by Cocos labels and game configuration; "
    "the artwork uses blank calm label areas, decorative leaf curls, paw motifs, "
    "stars, flowers, gems, ribbons, ropes, wood trims, soft cloth shapes, "
    "and simple geometric ornaments only. "
    "Safe world motif: flowers, leaves, mushrooms, crystals, coins, lanterns, "
    "books, tents, tools, clouds, stars, paw marks, soft magic sparkles, "
    "clean adventure props, warm camp details, peaceful ruins reclaimed by nature, "
    "and cheerful elemental scenery. "
    "Target canvas: 260x96. "
    "Runtime format intent: PNG RGBA workflow with clean alpha extraction "
    "when the asset needs transparency. "
    "Asset role: empty card background frame for the character selection screen. "
    "Shape concept: warm parchment-tone or soft translucent forest panel background card, "
    "leafy wooden border decoration, clean cream-tone content area in the center. "
    "The card interior is a blank empty area with subtle warm shading, "
    "ready for runtime Chinese labels and character avatar icons "
    "that will be overlaid by the engine. "
    "Decorative elements are limited to the card border only. "
    "Style consistency: same rounded line weight, same warm forest palette, "
    "same gem-and-leaf ornament language across every UI resource. "
    "Production note: artwork contains blank copy zones and decorative visual forms only; "
    "readable game copy is rendered by the engine."
)

# ===== 4. area_badge_forest.png — forest symbol, positive only =====
data['ui/area/area_badge_forest.png'] = (
    "Unified visual direction: bright cheerful cartoon adventure, "
    "warm hand-painted animation look, rounded friendly shapes, "
    "soft forest light, clean toy-like materials, saturated natural colors, "
    "gentle highlights, clear mobile readability, cozy family-safe fantasy mood, "
    "consistent with the integrated forest-and-gem interface style used by the current game. "
    "Release quality target: crisp confident outlines, clean alpha-ready edges, "
    "high-resolution details, smooth color gradients, polished lighting, "
    "readable silhouette, balanced contrast for small mobile screens, "
    "refined shape language, stable colors across the asset set. "
    "Runtime copy rule: all readable copy is provided by Cocos labels and game configuration; "
    "the artwork uses blank calm label areas, decorative leaf curls, paw motifs, "
    "stars, flowers, gems, ribbons, ropes, wood trims, soft cloth shapes, "
    "and simple geometric ornaments only. "
    "Safe world motif: flowers, leaves, mushrooms, crystals, coins, lanterns, "
    "books, tents, tools, clouds, stars, paw marks, soft magic sparkles, "
    "clean adventure props, warm camp details, peaceful ruins reclaimed by nature, "
    "and cheerful elemental scenery. "
    "Target canvas: 128x128. "
    "Runtime format intent: PNG RGBA workflow with clean alpha extraction "
    "for transparent badge overlay. "
    "Asset role: small region badge emblem for the area screen. "
    "Visual subject: a forest-themed circular emblem representing the Forest region. "
    "The badge center features a simple tree silhouette or leaf cluster, "
    "surrounded by a round warm-wood or leaf-rimmed border, "
    "with a small gem accent at the bottom or top. "
    "The design is a symbolic emblem using plant and gem motifs, "
    "readable at small size with clear contour and simple silhouette. "
    "Style consistency: same rounded line weight, same warm forest palette, "
    "same gem-and-leaf ornament language across every UI resource. "
    "Production note: artwork contains blank copy zones and decorative visual forms only; "
    "readable game copy is rendered by the engine."
)

# ===== 5. icon_item_key.png — key icon, positive only, plus matte hint =====
data['icons/items/icon_item_key.png'] = (
    "Unified visual direction: bright cheerful cartoon adventure, "
    "warm hand-painted animation look, rounded friendly shapes, "
    "soft forest light, clean toy-like materials, saturated natural colors, "
    "gentle highlights, clear mobile readability, cozy family-safe fantasy mood, "
    "consistent with the integrated forest-and-gem interface style used by the current game. "
    "Release quality target: crisp confident outlines, clean alpha-ready edges, "
    "high-resolution details, smooth color gradients, polished lighting, "
    "readable silhouette, balanced contrast for small mobile screens, "
    "refined shape language, stable colors across the asset set. "
    "Runtime copy rule: all readable copy is provided by Cocos labels and game configuration; "
    "the artwork uses blank calm label areas, decorative leaf curls, paw motifs, "
    "stars, flowers, gems, ribbons, ropes, wood trims, soft cloth shapes, "
    "and simple geometric ornaments only. "
    "Target canvas: 128x128. "
    "Runtime format intent: PNG RGBA workflow with clean alpha extraction "
    "for transparent icon. "
    "Segmentation setup: the subject sits on a plain warm beige matte background "
    "with the matte color clearly distinct from the subject for clean alpha extraction. "
    "Asset role: standalone inventory icon. "
    "Icon concept: a classic antique-style key with a round decorative bow "
    "at the top and two clean teeth at the bottom, "
    "warm golden brass or aged bronze metallic color, "
    "soft top-left highlight giving metallic reflection, "
    "subtle warm shadow on the right side for depth, "
    "thick soft outline for readability at small size. "
    "Composition: one centered object filling roughly 60-70 percent of the canvas, "
    "simple readable silhouette at 64px, distinct bright metal color "
    "that stands out clearly from the beige matte background. "
    "Small-scale readability: recognizable at 64px, "
    "clean center placement, consistent icon lighting across the icon set."
)

# Save
with open('E:/game/assets/resources/config/prompts.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("5 prompts updated with positive-only descriptions")