import json

with open('E:/game/assets/resources/config/prompts.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# ===== 1. splash_bg.jpg =====
data['ui/splash/splash_bg.jpg'] = (
    "Unified visual direction: bright cheerful cartoon adventure, "
    "warm hand-painted animation look, rounded friendly shapes, "
    "soft forest light, clean toy-like materials, saturated natural colors, "
    "gentle highlights, clear mobile readability, cozy family-safe fantasy mood, "
    "consistent with the integrated forest-and-gem interface style used by the current game. "
    "Release quality target: crisp confident outlines, clean edges, "
    "high-resolution details, smooth color gradients, polished lighting, "
    "well-balanced composition, refined shape language, stable colors across the asset set. "
    "Runtime copy rule: all readable copy is provided by Cocos labels and game configuration; "
    "the artwork uses blank calm label areas, decorative leaf curls, paw motifs, "
    "stars, flowers, gems, ribbons, ropes, wood trims, soft cloth shapes, "
    "and simple geometric ornaments only. "
    "Safe world motif: flowers, leaves, mushrooms, crystals, coins, lanterns, "
    "books, tents, tools, clouds, stars, paw marks, soft magic sparkles, "
    "clean adventure props, warm camp details, peaceful ruins reclaimed by nature, "
    "and cheerful elemental scenery. "
    "Target canvas: 1280x720. "
    "Runtime format intent: full opaque rectangular image with rich color "
    "and smooth gradients for JPG export. "
    "Asset role: atmospheric background for the splash screen. "
    "Scene concept: wide forest camp scene viewed from a distance, "
    "gentle morning light through trees, open calm meadow in the center area, "
    "no close-up characters or decorative frame, "
    "the center-left area should be clear low-detail open space "
    "to accommodate title text and game logo overlay, "
    "the bottom area should be calm unobtrusive ground detail "
    "to accommodate menu buttons. "
    "Composition: wide panoramic landscape view, horizon in the lower third, "
    "soft sky gradient at top, reserved open meadow space in the middle for title overlay, "
    "subtle path or river leading into the distance. "
    "No characters, no animals, no portraits. "
    "The reserved areas use calm low-detail lighting, soft ground glow, "
    "gentle shadows, and blank readable surfaces. "
    "Style consistency: same rounded line weight, same warm forest palette, "
    "same gem-and-leaf ornament language across every UI resource. "
    "Production note: artwork contains blank copy zones and decorative visual forms only; "
    "readable game copy is rendered by the engine."
)

# ===== 2. btn_create_confirm.png =====
data['ui/create/btn_create_confirm.png'] = (
    "Unified visual direction: bright cheerful cartoon adventure, "
    "warm hand-painted animation look, rounded friendly shapes, "
    "soft forest light, clean toy-like materials, saturated natural colors, "
    "gentle highlights, clear mobile readability, cozy family-safe fantasy mood, "
    "consistent with the integrated forest-and-gem interface style used by the current game. "
    "Release quality target: crisp confident outlines, clean alpha-ready edges, "
    "high-resolution details, smooth color gradients, polished lighting, "
    "readable silhouette, balanced contrast for small mobile screens, "
    "refined shape language, stable colors across the asset set. "
    "Runtime copy rule: all readable copy is provided by Cocos labels and game configuration; "
    "the artwork uses blank calm label areas, decorative leaf curls, paw motifs, "
    "stars, flowers, gems, ribbons, ropes, wood trims, soft cloth shapes, "
    "and simple geometric ornaments only. "
    "Safe world motif: flowers, leaves, mushrooms, crystals, coins, lanterns, "
    "books, tents, tools, clouds, stars, paw marks, soft magic sparkles, "
    "clean adventure props, warm camp details, peaceful ruins reclaimed by nature, "
    "and cheerful elemental scenery. "
    "Target canvas: 240x80. "
    "Runtime format intent: PNG RGBA workflow with clean alpha extraction "
    "for transparent button overlay. "
    "Asset role: runtime label button frame for the create screen. "
    "Shape concept: a raised rounded rectangular button with gentle drop shadow, "
    "beveled edges suggesting pressability, warm wooden texture, subtle wood grain, "
    "slight inner highlight giving a 3D raised appearance. "
    "No decorative frame or plaque. No characters. "
    "Decorative leaves and gem accents at left and right ends very subtly placed, "
    "but the overall shape must clearly read as a clickable button "
    "with a calm blank center for runtime label. "
    "Clean alpha edge for transparent overlay. "
    "Style consistency: same rounded line weight, same warm forest palette, "
    "same gem-and-leaf ornament language across every UI resource. "
    "Production note: artwork contains blank copy zones and decorative visual forms only; "
    "readable game copy is rendered by the engine."
)

# ===== 3. character_card_default.png =====
data['ui/character/character_card_default.png'] = (
    "Unified visual direction: bright cheerful cartoon adventure, "
    "warm hand-painted animation look, rounded friendly shapes, "
    "soft forest light, clean toy-like materials, saturated natural colors, "
    "gentle highlights, clear mobile readability, cozy family-safe fantasy mood, "
    "consistent with the integrated forest-and-gem interface style used by the current game. "
    "Release quality target: crisp confident outlines, clean alpha-ready edges, "
    "high-resolution details, smooth color gradients, polished lighting, "
    "readable silhouette, balanced contrast for small mobile screens, "
    "refined shape language, stable colors across the asset set. "
    "Runtime copy rule: all readable copy is provided by Cocos labels and game configuration; "
    "the artwork uses blank calm label areas, decorative leaf curls, paw motifs, "
    "stars, flowers, gems, ribbons, ropes, wood trims, soft cloth shapes, "
    "and simple geometric ornaments only. "
    "Safe world motif: flowers, leaves, mushrooms, crystals, coins, lanterns, "
    "books, tents, tools, clouds, stars, paw marks, soft magic sparkles, "
    "clean adventure props, warm camp details, peaceful ruins reclaimed by nature, "
    "and cheerful elemental scenery. "
    "Target canvas: 260x96. "
    "Runtime format intent: PNG RGBA workflow with clean alpha extraction "
    "when the asset needs transparency. "
    "Asset role: empty content card frame for the character screen. "
    "Shape concept: warm parchment or soft translucent forest panel background card, "
    "leafy wooden border, gem corner details, quiet cream content area, "
    "clean stretchable bands for scalable UI. "
    "IMPORTANT: this is an empty card frame with no character inside. "
    "The card interior must be a blank calm area with subtle warm shading "
    "and no subject matter of any kind, "
    "reserved for runtime Chinese labels and icons that will be overlaid by the engine. "
    "No animals, no characters, no portraits inside the card. "
    "Style consistency: same rounded line weight, same warm forest palette, "
    "same gem-and-leaf ornament language across every UI resource. "
    "Production note: artwork contains blank copy zones and decorative visual forms only; "
    "readable game copy is rendered by the engine."
)

# ===== 4. area_badge_forest.png =====
data['ui/area/area_badge_forest.png'] = (
    "Unified visual direction: bright cheerful cartoon adventure, "
    "warm hand-painted animation look, rounded friendly shapes, "
    "soft forest light, clean toy-like materials, saturated natural colors, "
    "gentle highlights, clear mobile readability, cozy family-safe fantasy mood, "
    "consistent with the integrated forest-and-gem interface style used by the current game. "
    "Release quality target: crisp confident outlines, clean alpha-ready edges, "
    "high-resolution details, smooth color gradients, polished lighting, "
    "readable silhouette, balanced contrast for small mobile screens, "
    "refined shape language, stable colors across the asset set. "
    "Runtime copy rule: all readable copy is provided by Cocos labels and game configuration; "
    "the artwork uses blank calm label areas, decorative leaf curls, paw motifs, "
    "stars, flowers, gems, ribbons, ropes, wood trims, soft cloth shapes, "
    "and simple geometric ornaments only. "
    "Safe world motif: flowers, leaves, mushrooms, crystals, coins, lanterns, "
    "books, tents, tools, clouds, stars, paw marks, soft magic sparkles, "
    "clean adventure props, warm camp details, peaceful ruins reclaimed by nature, "
    "and cheerful elemental scenery. "
    "Target canvas: 128x128. "
    "Runtime format intent: PNG RGBA workflow with clean alpha extraction "
    "for transparent badge overlay. "
    "Asset role: small region badge emblem for the area screen. "
    "Visual subject: A forest-themed circular emblem symbolizing the Forest region. "
    "Depict a simple centered tree silhouette or leaf cluster as the main symbol, "
    "inside a round warm-wood or leaf-rimmed badge, "
    "with a small gem accent at the bottom or top. "
    "No character, no animal, no portrait - only symbolic forest elements "
    "(tree, leaf, acorn, mushroom cluster). "
    "The badge must be recognizable at small size "
    "with clear contour and simple readable silhouette. "
    "Style consistency: same rounded line weight, same warm forest palette, "
    "same gem-and-leaf ornament language across every UI resource. "
    "Production note: artwork contains blank copy zones and decorative visual forms only; "
    "readable game copy is rendered by the engine."
)

# ===== 5. icon_item_key.png =====
data['icons/items/icon_item_key.png'] = (
    "Unified visual direction: bright cheerful cartoon adventure, "
    "warm hand-painted animation look, rounded friendly shapes, "
    "soft forest light, clean toy-like materials, saturated natural colors, "
    "gentle highlights, clear mobile readability, cozy family-safe fantasy mood, "
    "consistent with the integrated forest-and-gem interface style used by the current game. "
    "Release quality target: crisp confident outlines, clean alpha-ready edges, "
    "high-resolution details, smooth color gradients, polished lighting, "
    "readable silhouette, balanced contrast for small mobile screens, "
    "refined shape language, stable colors across the asset set. "
    "Runtime copy rule: all readable copy is provided by Cocos labels and game configuration; "
    "the artwork uses blank calm label areas, decorative leaf curls, paw motifs, "
    "stars, flowers, gems, ribbons, ropes, wood trims, soft cloth shapes, "
    "and simple geometric ornaments only. "
    "Target canvas: 128x128. "
    "Runtime format intent: PNG RGBA workflow with clean alpha extraction "
    "for transparent icon. "
    "Segmentation setup: isolated subject on a plain warm beige "
    "or light wood-toned matte background for alpha extraction, "
    "subject centered with even breathing room, "
    "matte color should be clearly distinct from the key color "
    "so flood-fill removal can cleanly separate them. "
    "Asset role: standalone inventory icon. "
    "Icon concept: a classic antique-style key with a round decorative bow "
    "(ornamental loop at the top) and two clean teeth, "
    "warm golden brass or aged bronze color, "
    "soft top-left highlight, subtle warm shadow on the right side, "
    "thick soft outline for readability. "
    "Composition: one centered object, simple readable silhouette at 64px, "
    "rich but clean colors, no other objects or background details. "
    "The key must be visually solid with clear contrast against the matte background. "
    "Small-scale readability: recognizable at 64px, "
    "uncluttered center, consistent icon lighting and border thickness across the icon set."
)

# Save
with open('E:/game/assets/resources/config/prompts.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("5 prompts updated successfully")
print(f"Total keys: {len(data)}")
