#!/usr/bin/env python3
"""Fix prompts to add edge margin / breathing room instructions."""
import json

with open('E:/game/assets/resources/config/prompts.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# ===== btn_create_confirm.png: add breathing room around the button frame =====
data['ui/create/btn_create_confirm.png'] = (
    "Unified visual direction: bright cheerful cartoon adventure, "
    "warm hand-painted animation look, rounded friendly shapes, "
    "soft forest light, clean toy-like materials, saturated natural colors, "
    "gentle highlights, clear mobile readability, cozy family-safe fantasy mood, "
    "consistent with the integrated forest-and-gem interface style used by the current game. "
    "Release quality target: crisp confident outlines, clean alpha-ready edges, "
    "high-resolution details, smooth color gradients, polished lighting, "
    "readable silhouette, balanced contrast for small mobile screens, "
    "refined shape language, stable colors across the asset set. "
    "Runtime copy rule: all readable copy is provided by Cocos labels and game configuration; "
    "the artwork uses blank calm label areas, decorative leaf curls, paw motifs, "
    "stars, flowers, gems, ribbons, ropes, wood trims, soft cloth shapes, "
    "and simple geometric ornaments only. "
    "Safe world motif: flowers, leaves, mushrooms, crystals, coins, lanterns, "
    "books, tents, tools, clouds, stars, paw marks, soft magic sparkles, "
    "clean adventure props, warm camp details, peaceful ruins reclaimed by nature, "
    "and cheerful elemental scenery. "
    "Target canvas: 240x80. "
    "Runtime format intent: PNG RGBA workflow with clean alpha extraction "
    "for transparent button overlay. "
    "Asset role: clickable raised button frame for the create screen. "
    "Shape concept: a raised rounded rectangular button with gentle drop shadow, "
    "beveled edges suggesting pressability, warm wooden texture, subtle wood grain, "
    "slight inner highlight giving a 3D raised appearance. "
    "The overall shape clearly reads as a clickable button, "
    "with a calm blank center area reserved for runtime label text. "
    "Very subtle decorative leaves and gem accents at left and right ends. "
    "Edge margin rule: the button frame must sit well inside the canvas with generous "
    "empty space on all four sides, so the rounded corners and decorative details "
    "remain fully visible and are never truncated by the image border. "
    "Clean alpha edge for transparent overlay. "
    "Style consistency: same rounded line weight, same warm forest palette, "
    "same gem-and-leaf ornament language across every UI resource. "
    "Production note: artwork contains blank copy zones and decorative visual forms only; "
    "readable game copy is rendered by the engine."
)

# ===== character_card_default.png: add padding around the card frame =====
data['ui/character/character_card_default.png'] = (
    "Unified visual direction: bright cheerful cartoon adventure, "
    "warm hand-painted animation look, rounded friendly shapes, "
    "soft forest light, clean toy-like materials, saturated natural colors, "
    "gentle highlights, clear mobile readability, cozy family-safe fantasy mood, "
    "consistent with the integrated forest-and-gem interface style used by the current game. "
    "Release quality target: crisp confident outlines, clean alpha-ready edges, "
    "high-resolution details, smooth color gradients, polished lighting, "
    "readable silhouette, balanced contrast for small mobile screens, "
    "refined shape language, stable colors across the asset set. "
    "Runtime copy rule: all readable copy is provided by Cocos labels and game configuration; "
    "the artwork uses blank calm label areas, decorative leaf curls, paw motifs, "
    "stars, flowers, gems, ribbons, ropes, wood trims, soft cloth shapes, "
    "and simple geometric ornaments only. "
    "Safe world motif: flowers, leaves, mushrooms, crystals, coins, lanterns, "
    "books, tents, tools, clouds, stars, paw marks, soft magic sparkles, "
    "clean adventure props, warm camp details, peaceful ruins reclaimed by nature, "
    "and cheerful elemental scenery. "
    "Target canvas: 260x96. "
    "Runtime format intent: PNG RGBA workflow with clean alpha extraction "
    "when the asset needs transparency. "
    "Asset role: empty card background frame for the character selection screen. "
    "Shape concept: warm parchment-tone or soft translucent forest panel background card, "
    "leafy wooden border decoration, gem corner details, quiet cream content area in the center. "
    "The card interior is a blank empty area with subtle warm shading, "
    "ready for runtime Chinese labels and character avatar icons "
    "that will be overlaid by the engine. "
    "Decorative elements are limited to the card border only. "
    "Edge margin rule: the entire card frame must be inset from the canvas edge "
    "with generous empty space on all four sides, "
    "so the rounded corners, leaf border, and gem corners remain fully visible "
    "and are never truncated by the image border. "
    "Style consistency: same rounded line weight, same warm forest palette, "
    "same gem-and-leaf ornament language across every UI resource. "
    "Production note: artwork contains blank copy zones and decorative visual forms only; "
    "readable game copy is rendered by the engine."
)

# ===== area_badge_forest.png: keep emblem centered with margin =====
data['ui/area/area_badge_forest.png'] = (
    "Unified visual direction: bright cheerful cartoon adventure, "
    "warm hand-painted animation look, rounded friendly shapes, "
    "soft forest light, clean toy-like materials, saturated natural colors, "
    "gentle highlights, clear mobile readability, cozy family-safe fantasy mood, "
    "consistent with the integrated forest-and-gem interface style used by the current game. "
    "Release quality target: crisp confident outlines, clean alpha-ready edges, "
    "high-resolution details, smooth color gradients, polished lighting, "
    "readable silhouette, balanced contrast for small mobile screens, "
    "refined shape language, stable colors across the asset set. "
    "Runtime copy rule: all readable copy is provided by Cocos labels and game configuration; "
    "the artwork uses blank calm label areas, decorative leaf curls, paw motifs, "
    "stars, flowers, gems, ribbons, ropes, wood trims, soft cloth shapes, "
    "and simple geometric ornaments only. "
    "Safe world motif: flowers, leaves, mushrooms, crystals, coins, lanterns, "
    "books, tents, tools, clouds, stars, paw marks, soft magic sparkles, "
    "clean adventure props, warm camp details, peaceful ruins reclaimed by nature, "
    "and cheerful elemental scenery. "
    "Target canvas: 128x128. "
    "Runtime format intent: PNG RGBA workflow with clean alpha extraction "
    "for transparent badge overlay. "
    "Asset role: small region badge emblem for the area screen. "
    "Visual subject: a forest-themed circular emblem representing the Forest region. "
    "The badge center features a simple tree silhouette or leaf cluster, "
    "surrounded by a round warm-wood or leaf-rimmed border, "
    "with a small gem accent at the bottom or top. "
    "The design is a symbolic emblem using plant and gem motifs. "
    "Edge margin rule: the circular emblem is centered with generous empty space "
    "between the outer rim and the canvas edge on all four sides, "
    "so the badge is fully contained and never truncated by the image border. "
    "The badge must be recognizable at small size with clear contour and simple silhouette. "
    "Style consistency: same rounded line weight, same warm forest palette, "
    "same gem-and-leaf ornament language across every UI resource. "
    "Production note: artwork contains blank copy zones and decorative visual forms only; "
    "readable game copy is rendered by the engine."
)

# ===== icon_item_key.png: key centered with transparent margin =====
data['icons/items/icon_item_key.png'] = (
    "Unified visual direction: bright cheerful cartoon adventure, "
    "warm hand-painted animation look, rounded friendly shapes, "
    "soft forest light, clean toy-like materials, saturated natural colors, "
    "gentle highlights, clear mobile readability, cozy family-safe fantasy mood, "
    "consistent with the integrated forest-and-gem interface style used by the current game. "
    "Release quality target: crisp confident outlines, clean alpha-ready edges, "
    "high-resolution details, smooth color gradients, polished lighting, "
    "readable silhouette, balanced contrast for small mobile screens, "
    "refined shape language, stable colors across the asset set. "
    "Runtime copy rule: all readable copy is provided by Cocos labels and game configuration; "
    "the artwork uses blank calm label areas, decorative leaf curls, paw motifs, "
    "stars, flowers, gems, ribbons, ropes, wood trims, soft cloth shapes, "
    "and simple geometric ornaments only. "
    "Target canvas: 128x128. "
    "Runtime format intent: PNG RGBA workflow with clean alpha extraction "
    "for transparent icon. "
    "Segmentation setup: isolated subject on a plain warm beige "
    "or light wood-toned matte background for alpha extraction, "
    "subject centered with even breathing room, "
    "matte color should be clearly distinct from the key color "
    "so flood-fill removal can cleanly separate them. "
    "Asset role: standalone inventory icon. "
    "Icon concept: a classic antique-style key with a round decorative bow "
    "at the top and two clean teeth at the bottom, "
    "warm golden brass or aged bronze metallic color, "
    "soft top-left highlight giving metallic reflection, "
    "subtle warm shadow on the right side for depth, "
    "thick soft outline for readability at small size. "
    "Edge margin rule: the key is centered with generous empty matte space "
    "between the key outline and the canvas edge on all four sides, "
    "so the key silhouette is fully contained and never truncated by the image border. "
    "Composition: one centered object filling roughly 60 percent of the canvas, "
    "simple readable silhouette at 64px, rich but clean colors, "
    "no other objects or background details. "
    "The key must be visually solid with clear contrast against the matte background. "
    "Small-scale readability: recognizable at 64px, "
    "clean center placement, consistent icon lighting across the icon set."
)

# Save
with open('E:/game/assets/resources/config/prompts.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("4 prompts updated with edge margin rules")
