#!/usr/bin/env python3
"""
gen_game_assets.py — Generate game_assets.json from existing texture files.

Reads all texture files in assets/resources/textures/, categorizes them,
and emits a game_assets.json with best-guess metadata.

Usage:
    python tools/gen_game_assets.py > assets/resources/config/game_assets.json
    python tools/gen_game_assets.py --pretty > assets/resources/config/game_assets.json
"""

import json
import os
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
PROJECT_DIR = SCRIPT_DIR.parent
TEXTURES_DIR = PROJECT_DIR / "assets" / "resources" / "textures"

# Known sprite sheet frame sizes from SpriteSheetUtil.ts + file size heuristics
# (frameWidth, frameHeight, frames, layout)
SHEET_METADATA: dict[str, tuple[int, int, int, str]] = {
    # Characters: known 192x192, 4 frames, vertical
    **{f"characters/{c}/{a}": (192, 192, 4, "vertical")
       for c in ["warrior", "archer", "assassin", "berserker", "mage"]
       for a in ["idle", "walk", "attack", "hit", "dodge", "skill", "death"]},
    # archer_attack regenerated at 256x256 (per ART_RESOURCE_RULES.md section 9/15:
    # character sprite sheet = 256x1024, 4 frames @ 256x256 vertical). Override to
    # keep registry aligned with the 256x1024 asset and the current spec.
    "characters/archer/archer_attack": (256, 256, 4, "vertical"),
}


def generate() -> dict:
    assets = {}
    metadata = {
        "version": "1.0.0",
        "lastUpdated": "2026-07-06",
        "description": "Non-UI art semantic registry. Generated by gen_game_assets.py",
        "generated": True,
        "safeReview": False,
    }
    assets["metadata"] = metadata

    if not TEXTURES_DIR.exists():
        print(f"[ERROR] textures dir not found: {TEXTURES_DIR}", file=sys.stderr)
        return assets

    for root, dirs, files in os.walk(TEXTURES_DIR):
        for fname in sorted(files):
            ext = Path(fname).suffix.lower()
            if ext not in {".png", ".jpg", ".jpeg"}:
                continue

            full_path = Path(root) / fname
            # Relative path from textures/ like "characters/warrior/warrior_idle.png"
            rel = full_path.relative_to(TEXTURES_DIR)
            stem = str(rel.with_suffix("")).replace("\\", "/")

            # Build semantic key
            if stem.startswith("characters/"):
                parts = stem.split("/")
                char_id = parts[1]  # e.g. warrior
                action = parts[2]   # e.g. idle
                # Remove char prefix from action if present
                for prefix in ["warrior_", "archer_", "assassin_", "berserker_", "mage_"]:
                    action = action.replace(prefix, "")
                key = f"character.{char_id}.{action}"

            elif stem.startswith("monsters/"):
                parts = stem.split("/")
                zone = parts[1]
                # monster_forest_slime_idle -> forest_slime
                mname = parts[2].replace(f"monster_{zone}_", "").replace("_idle", "").replace("_walk", "").replace("_attack", "").replace("_hit", "").replace("_death", "").replace("_dodge", "").replace("_skill", "")
                key = f"monster.{zone}.{mname}"

            elif stem.startswith("bosses/finalboss/"):
                bname = stem.split("/")[-1]
                # boss_abyssoverlord_idle -> abyssoverlord
                for prefix in ["boss_", "_idle", "_attack", "_skill", "_death", "_phasechange"]:
                    bname = bname.replace(prefix, "")
                # Determine boss id
                bn = stem.split("/")[-1].replace("boss_", "")
                for suffix in ["_idle", "_attack", "_skill", "_death", "_phasechange"]:
                    bn = bn.replace(suffix, "")
                key = f"boss.{bn}"

            elif stem.startswith("backgrounds/"):
                bname = stem.split("/")[-1]
                key = f"background.{bname}"

            elif stem.startswith("tiles/"):
                parts = stem.split("/")
                zone = parts[1]
                tname = parts[2].replace(f"tile_{zone}_", "")
                key = f"tile.{zone}.{tname}"

            elif stem.startswith("effects/"):
                parts = stem.split("/")
                subdir = parts[1]
                ename = parts[2]
                # Map to effect type
                if subdir == "combat":
                    key = f"effect.combat.{ename.replace('fx_', '')}"
                elif subdir == "reactions":
                    key = f"effect.reaction.{ename.replace('fx_reaction_', '')}"
                elif subdir == "relics":
                    key = f"effect.relic.{ename.replace('fx_relic_', '').replace('_', '')}"
                elif subdir == "ui":
                    key = f"effect.ui.{ename.replace('fx_ui_', '')}"
                else:
                    key = f"effect.{subdir}.{ename}"

            elif stem.startswith("icons/"):
                parts = stem.split("/")
                subdir = parts[1]
                iname = parts[2]
                key = f"icon.{subdir}.{iname}"

            elif stem.startswith("ui/"):
                continue  # UI resources handled by ui_assets.json

            else:
                continue  # Unknown category, skip

            # Determine type and metadata
            asset_id = f"textures/{stem}"

            entry = {"assetId": asset_id}

            if stem in SHEET_METADATA:
                fw, fh, fc, layout = SHEET_METADATA[stem]
                entry["type"] = "sprite_sheet"
                entry["category"] = stem.split("/")[0]
                entry["frameWidth"] = fw
                entry["frameHeight"] = fh
                entry["frames"] = fc
                entry["layout"] = layout
                fw, fh, fc, layout = SHEET_METADATA[stem]
                entry["type"] = "sprite_sheet"
                entry["category"] = stem.split("/")[0]
                entry["frameWidth"] = fw
                entry["frameHeight"] = fh
                entry["frames"] = fc
                entry["layout"] = layout
            elif stem.startswith("backgrounds/"):
                entry["type"] = "background"
                entry["category"] = "background"
                entry["format"] = ext.lstrip(".")
                entry["fit"] = "cover"
            elif stem.startswith("tiles/"):
                entry["type"] = "tile"
                entry["category"] = "tile"
                entry["tileSize"] = 32
                entry["seamless"] = True
            elif stem.startswith("effects/"):
                if "reaction" in stem or "relic" in stem:
                    entry["type"] = "effect_sheet"
                    entry["frameWidth"] = 192
                    entry["frameHeight"] = 192
                    entry["frames"] = 4
                    entry["layout"] = "vertical"
                    if "relic" in stem:
                        entry["blendMode"] = "additive"
                else:
                    entry["type"] = "sprite"
                    entry["category"] = "effect"
            elif stem.startswith("icons/"):
                entry["type"] = "icon"
                entry["category"] = "icon"
                entry["width"] = 128
                entry["height"] = 128
                entry["transparent"] = True
            else:
                entry["type"] = "sprite"
                entry["category"] = stem.split("/")[0]

            entry["safeReview"] = False

            # De-duplicate: monsters may have multiple files mapping to same semantic key
            base_key = key
            dedup_idx = 2
            while base_key in assets:
                base_key = f"{key}_{dedup_idx}"
                dedup_idx += 1
            key = base_key

            assets[key] = entry

    return assets


def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument("--pretty", action="store_true", help="Pretty-print output")
    args = parser.parse_args()

    result = generate()
    indent = 2 if args.pretty else None
    json.dump(result, sys.stdout, ensure_ascii=False, indent=indent)


if __name__ == "__main__":
    main()
